now via gh actions

diff --git a/mise/tasks/package b/mise/tasks/package
--- a/mise/tasks/package
+++ b/mise/tasks/package
@@ -34,11 +34,11 @@ for f in "${FILES[@]}"; do
    fi
 done
 
+# Set NPM version
 (
    cd npm || exit 1
    npm version $VERSION --no-git-tag-version
 )
-
 
 # If GH_TOKEN is not defined, print a warning and exit 0
 if [[ -z ${GH_TOKEN+x} || -z ${GITHUB_SHA+x} ]]; then
@@ -48,3 +48,14 @@ fi
 
 gh release create "$VERSION" --target "$GITHUB_SHA" --title "md-social $VERSION" --generate-notes
 gh release upload "$VERSION" dist/*.zip dist/*.gz
+
+# Publish to NPM
+if [[ -z ${NPM_TOKEN+x} ]]; then
+  echo "Warning: Unable to publish to NPM. NPM_TOKEN is missing."
+  exit 0
+fi
+
+(
+   cd npm || exit 1
+   npm publish
+)
